excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods

disabled_rules: # rule identifiers to exclude from running
  - cyclomatic_complexity
  - empty_enum_arguments
  - large_tuple

line_length: 160

force_cast: warning # implicitly

force_try:
    severity: warning # explicitly

file_length:
 warning: 500
 error: 1200

type_body_length:
 warning: 300
 error: 700

type_name:
 min_length: 4 # only warning
 max_length: # warning and error
  warning: 50
  error: 50
 excluded: # excluded via string array
  - UP
  - ON
  - OFF
  - Key

function_parameter_count: 5
