platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'Le Monde RSS' do
	pod 'Alamofire'
    pod 'AlamofireImage', '~> 3.3'
	pod 'XMLMapper/Requests'
    pod 'TTGSnackbar'
end

target 'Le Monde RSSTests' do
    inherit! :search_paths

  end

